homework 1
KulR/2018-FS-21-Frontend-Kulikov pull request #1
Opened 2018-10-02 09:01 UTC by KulR

Function "say" adds block with a color other than the background

2018-10-02 20:54 UTC, martinkomitsky commented on .gitignore
> +node_modules
Нужно добавить папку `/dist` сюда, а ее содержимое удалить. Сборки не должны храниться в репозиториях

2018-10-02 20:54 UTC, martinkomitsky commented on hw1/dist/main.js
> +/******/ (function(modules) { // webpackBootstrap
Удалить файл

2018-10-02 20:58 UTC, martinkomitsky commented on hw1/src/lib/test.js
> +    var div = document.createElement("p");
Привыкаем к правильному `code style`. В `js` все строчные значение пишем одинарными кавычками `'`. Мешанины из двойных и одинарных кавычек быть не должно

2018-10-02 21:00 UTC, martinkomitsky commented on hw1/static/task1.css
> +.block{
Опять, к слову о `code style`. Привыкаем ставить пробелы после названий классов, а последующие правила, которые идут со смещением (после открытия фигурной скобки) либо смещать на 4 пробела, либо на один таб. Опять, мешанины из табов и пробелов быть не должно.

2018-10-02 21:02 UTC, martinkomitsky requested changes
Исправить замечания

2018-10-03 14:14 UTC, KulR commented on .gitignore
> +node_modules
fixed

2018-10-03 14:14 UTC, KulR commented on hw1/dist/main.js
> +/******/ (function(modules) { // webpackBootstrap
fixed

2018-10-03 14:14 UTC, KulR commented on hw1/src/lib/test.js
> +    var div = document.createElement("p");
fixed

2018-10-03 14:14 UTC, KulR commented on hw1/static/task1.css
> +.block{
fixed

2018-10-03 14:15 UTC, martinkomitsky approved these changes

2018-10-03 14:15 UTC, merged

2018-10-03 14:15 UTC, martinkomitsky commented
10